# Generated by Django 4.2.4 on 2023-08-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('sueldo_total', models.FloatField()),
            ],
        ),
    ]
